upadted docker files

diff --git a/.github/workflows/cd_frontend.yml b/.github/workflows/cd_frontend.yml
--- a/.github/workflows/cd_frontend.yml
+++ b/.github/workflows/cd_frontend.yml
@@ -8,6 +8,7 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
       - uses: actions/checkout@v4
 
@@ -36,5 +37,21 @@ jobs:
           key: ${{ secrets.SSH_KEY }}
           script: |
             cd /home/ubuntu/week-27-monorepodeployment
-            docker compose -f ./docker-compose.yml pull app
-            docker compose -f ./docker-compose.yml up -d  app
+            docker compose -f docker-compose.yml pull app
+            docker compose -f docker-compose.yml up -d app
+
+      - name: Verify secrets
+        run: |
+          if [ -n "${{ secrets.NEXT_PUBLIC_API_URL }}" ]; then
+            echo "✅ NEXT_PUBLIC_API_URL is set"
+          else
+            echo "❌ NEXT_PUBLIC_API_URL is missing"
+            exit 1
+          fi
+
+          if [ -n "${{ secrets.NEXT_PUBLIC_WS_URL }}" ]; then
+            echo "✅ NEXT_PUBLIC_WS_URL is set"
+          else
+            echo "❌ NEXT_PUBLIC_WS_URL is missing"
+            exit 1
+          fi
